spring:
  application:
    name: central-safety-system
  config:
    name: application.*, ${spring.application.name}*.*, ${spring.application.name}-logback-spring.xml
  jackson:
    default-property-inclusion: non-empty
  http:
    log-request-details: true
  profiles:
    active: local

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        
server:
  port: 9090

logging:
  config: classpath:${spring.application.name}-logback-spring.xml
  path: /logs/${spring.application.name}/
  file: /logs/${spring.application.name}/${spring.application.name}
# LOGGING
  level:
    root: warn
    org.springframework.core: warn
    org.springframework.beans: warn
    org.springframework.context: warn
    org.springframework.transaction: warn
    org.springframework.test: warn
    org.springframework.web: error
    org.hibernate: ERROR
    com.db.lemiecarte: debug
    
